export const COLLAPSE_NAV = 'nav/COLLAPSE_NAV'
export const UPDATE_BREADCRUMB = 'menu/UPDATE_BREADCRUMB'

export const FETCH_LOGIN_REQUEST = 'auth/FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'auth/FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILED = 'auth/FETCH_LOGIN_FAILED'

export const FETCH_LOGOUT_REQUEST = 'auth/FETCH_LOGOUT_REQUEST'
export const FETCH_LOGOUT_SUCCESS = 'auth/FETCH_LOGOUT_SUCCESS'
export const FETCH_LOGOUT_FAILED = 'auth/FETCH_LOGOUT_FAILED'

// 获取预定义列表
export const FETCH_PREDEFINE_ACTIONS_REQUEST = 'predefine/FETCH_PREDEFINE_ACTIONS_REQUEST'
export const FETCH_PREDEFINE_ACTIONS_SUCCESS = 'predefine/FETCH_PREDEFINE_ACTIONS_SUCCESS'
export const FETCH_PREDEFINE_ACTIONS_FAILED = 'predefine/FETCH_PREDEFINE_ACTIONS_FAILED'

export const ADD_PREDEFINE_ACTION_REQUEST = 'predefine/ADD_PREDEFINE_ACTION_REQUEST'
export const ADD_PREDEFINE_ACTION_SUCCESS = 'predefine/ADD_PREDEFINE_ACTION_SUCCESS'
export const ADD_PREDEFINE_ACTION_FAILED = 'predefine/ADD_PREDEFINE_ACTION_FAILED'

export const UPDATE_PREDEFINE_ACTION_REQUEST = 'predefine/UPDATE_PREDEFINE_ACTION_REQUEST'
export const UPDATE_PREDEFINE_ACTION_SUCCESS = 'predefine/UPDATE_PREDEFINE_ACTION_SUCCESS'
export const UPDATE_PREDEFINE_ACTION_FAILED = 'predefine/UPDATE_PREDEFINE_ACTION_FAILED'

export const DELETE_PREDEFINE_ACTION_REQUEST = 'predefine/DELETE_PREDEFINE_ACTION_REQUEST'
export const DELETE_PREDEFINE_ACTION_SUCCESS = 'predefine/DELETE_PREDEFINE_ACTION_SUCCESS'
export const DELETE_PREDEFINE_ACTION_FAILED = 'predefine/DELETE_PREDEFINE_ACTION_FAILED'

export const FETCH_PREDEFINE_ACTION_REQUEST = 'predefine/FETCH_PREDEFINE_ACTION_REQUEST'
export const FETCH_PREDEFINE_ACTION_SUCCESS = 'predefine/FETCH_PREDEFINE_ACTION_SUCCESS'
export const FETCH_PREDEFINE_ACTION_FAILED = 'predefine/FETCH_PREDEFINE_ACTION_FAILED'

export const FIND_TEMP_BY_ID_REQUEST = 'predefine/FIND_TEMP_BY_ID_REQUEST'
export const FIND_TEMP_BY_ID_SUCCESS = 'predefine/FIND_TEMP_BY_ID_SUCCESS'
export const FIND_TEMP_BY_ID_FAILED = 'predefine/FIND_TEMP_BY_ID_FAILED'

export const FIND_XLIST_BY_ID_REQUEST = 'predefine/FIND_XLIST_BY_ID_REQUEST'
export const FIND_XLIST_BY_ID_SUCCESS = 'predefine/FIND_XLIST_BY_ID_SUCCESS'
export const FIND_XLIST_BY_ID_FAILED = 'predefine/FIND_XLIST_BY_ID_FAILED'

export const FIND_ACTIONS_BY_IDS_REQUEST = 'predefine/FIND_ACTIONS_BY_IDS_REQUEST'
export const FIND_ACTIONS_BY_IDS_SUCCESS = 'predefine/FIND_ACTIONS_BY_IDS_SUCCESS'
export const FIND_ACTIONS_BY_IDS_FAILED = 'predefine/FIND_ACTIONS_BY_IDS_FAILED'

export const FIND_ARTICLE_BY_ID_REQUEST = 'predefine/FIND_ARTICLE_BY_ID_REQUEST'
export const FIND_ARTICLE_BY_ID_SUCCESS = 'predefine/FIND_ARTICLE_BY_ID_SUCCESS'
export const FIND_ARTICLE_BY_ID_FAILED = 'predefine/FIND_ARTICLE_BY_ID_FAILED'

// 通过动作actid查询出优惠券活动id请求
export const FETCH_COUPONID_BY_ACTID_REQUEST = 'coupon/FETCH_COUPONID_BY_ACTID_REQUEST'
export const FETCH_COUPONID_BY_ACTID_SUCCESS = 'coupon/FETCH_COUPONID_BY_ACTID_SUCCESS'
export const FETCH_COUPONID_BY_ACTID_FAILED = 'coupon/FETCH_COUPONID_BY_ACTID_FAILED'

// 批量增加优惠券上传文件请求
export const UPLOAD_COUPON_FOR_ADD_REQUEST = 'coupon/UPLOAD_COUPON_FOR_ADD_REQUEST'
export const UPLOAD_COUPON_FOR_ADD_SUCCESS = 'coupon/UPLOAD_COUPON_FOR_ADD_SUCCESS'
export const UPLOAD_COUPON_FOR_ADD_FAILED = 'coupon/UPLOAD_COUPON_FOR_ADD_FAILED'

// 批量删除优惠券上传文件请求
export const UPLOAD_COUPON_FOR_DELETE_REQUEST = 'coupon/UPLOAD_COUPON_FOR_DELETE_REQUEST'
export const UPLOAD_COUPON_FOR_DELETE_SUCCESS = 'coupon/UPLOAD_COUPON_FOR_DELETE_SUCCESS'
export const UPLOAD_COUPON_FOR_DELETE_FAILED = 'coupon/UPLOAD_COUPON_FOR_DELETE_FAILED'

// 优惠券管理列表列表
export const FETCH_COUPONS_REQUEST = 'coupon/FETCH_COUPONS_REQUEST'
export const FETCH_COUPONS_SUCCESS = 'coupon/FETCH_COUPONS_SUCCESS'
export const FETCH_COUPONS_FAILED = 'coupon/FETCH_COUPONS_FAILED'

// ftp上传到服务器上
export const TRANSFER_COUPONS_TO_FTP_REQUEST = 'coupon/TRANSFER_COUPONS_TO_FTP_REQUEST'
export const TRANSFER_COUPONS_TO_FTP_SUCCESS = 'coupon/TRANSFER_COUPONS_TO_FTP_SUCCESS'
export const TRANSFER_COUPONS_TO_FTP_FAILED = 'coupon/TRANSFER_COUPONS_TO_FTP_FAILED'

// 获取任务列表请求
export const FETCH_JOB_LIST_REQUEST = 'job/FETCH_JOB_LIST_REQUEST'
export const FETCH_JOB_LIST_SUCCESS = 'job/FETCH_JOB_LIST_SUCCESS'
export const FETCH_JOB_LIST_FAILED = 'job/FETCH_JOB_LIST_FAILED'

// 获取banner图片列表
export const FETCH_BANNER_LIST_REQUEST = 'banner/FETCH_BANNER_LIST_REQUEST'
export const FETCH_BANNER_LIST_SUCCESS = 'banner/FETCH_BANNER_LIST_SUCCESS'
export const FETCH_BANNER_LIST_FAILED = 'banner/FETCH_BANNER_LIST_FAILED'

// 修改banner上传到数据库
export const BANNER_UPDATE_UPLOAD_REQUEST = 'banner/BANNER_UPDATE_UPLOAD_REQUEST'
export const BANNER_UPDATE_UPLOAD_SUCCESS = 'banner/BANNER_UPDATE_UPLOAD_SUCCESS'
export const BANNER_UPDATE_UPLOAD_FAILED = 'banner/BANNER_UPDATE_UPLOAD_FAILED'

// 上传banner到数据库
export const BANNER_ADD_UPLOAD_REQUEST = 'banner/BANNER_ADD_UPLOAD_REQUEST'
export const BANNER_ADD_UPLOAD_SUCCESS = 'banner/BANNER_ADD_UPLOAD_SUCCESS'
export const BANNER_ADD_UPLOAD_FAILED = 'banner/BANNER_ADD_UPLOAD_FAILED'

// 用户角色列表
export const FETCH_USER_ROLES_REQUEST = 'user/FETCH_USER_ROLES_REQUEST'
export const FETCH_USER_ROLES_SUCCESS = 'user/FETCH_USER_ROLES_SUCCESS'
export const FETCH_USER_ROLES_FAILED = 'user/FETCH_USER_ROLES_FAILED'
